### PR TITLE
Closes #18 - Fixed draw order for edges and labels

### LINKED ISSUE #18: Edge Labels are drawn behind other edges
At the moment, it can happen that edges overlap with the edge-labels of other edges.
The drawing algorithm seems to do the following:
```
for each edge:
   drawEdge()
   drawLabel()
```

In my opinion, the labels should always be in the foreground and not accidentally overlapped by other edges.
This means we should isntead use the following algorithm:

```
for each edge:
   drawEdge()

for each edge:
   drawLabel()
```

### PR DESCRIPTION
**Pull request by JonasKunz**
This change is [Reviewable](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40)

### CODE REVIEW

**Review by mbrill-nt — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40)* status: all files reviewed, 1 unresolved discussion (waiting on @JonasKunz and @mariomann)

*[a discussion](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40#-MKYzUlPBnL78SYRgWq-:-MKYzUlQBpJ2ASjm-0vp:bjg6ea) (no related file):*
Most of this review appears to us like reorganisation. Could we talk so you can tell us where the fix actually takes place?

Also: Could you please upload the build version within this commit as we don't have a ci process yet.

---

**Review by mariomann — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40)* status: all files reviewed, 2 unresolved discussions (waiting on @JonasKunz)

*[a discussion](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40#-MK_CHRZ6XfVpJSdpnf0:-MK_CHR_20VHfGPUA1gz:b-ojbm6a) (no related file):*
Same comment as Marius, we need the build version within this commit in the dist folder. Please upload this as well in your commit.

---

**Review by JonasKunz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @mariomann and @mbrill-nt)

*[a discussion](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40#-MKYzUlPBnL78SYRgWq-:-MKnr1Ii3Epl2fRW6VR-:b-896fix) (no related file):*
<details><summary><i>Previously, mbrill-nt (Marius Brill) wrote…</i></summary><blockquote>

Most of this review appears to us like reorganisation. Could we talk so you can tell us where the fix actually takes place?

Also: Could you please upload the build version within this commit as we don't have a ci process yet.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40#-MK_CHRZ6XfVpJSdpnf0:-MKnr1YF91HUZPx7mruH:b-896fix) (no related file):*
<details><summary><i>Previously, mariomann (Mario Mann) wrote…</i></summary><blockquote>

Same comment as Marius, we need the build version within this commit in the dist folder. Please upload this as well in your commit.
</blockquote></details>

Done.

---

**Review by mariomann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @JonasKunz and @mbrill-nt)

*[a discussion](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40#-MKslVBu5dHYz8t89Drh:-MKslVBu5dHYz8t89Dri:b-uc6l9f) (no related file):*
I tested it and it doesn't work for me. Some edges are still in front of the label. For example:


Can you check it again, please.

---

**Review by mariomann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @MariusBrill)

**Review by MariusBrill — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40)* status: all files reviewed, 1 unresolved discussion (waiting on @MariusBrill)

**Review by MariusBrill — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/novatecconsulting/novatec-service-dependency-graph-panel/40)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
